### ISSUE TITLE
Dark Mode For AMOLED

### ISSUE THREAD

**Issue by darkhunterbg** [angelinn/TramlineFive.Xamarin#9]
Most modern phones uses AMOLED display, which consume less battery when parts of screen are darker/completly black.
Suggestion is to add dark theme similar to most popular apps (check Google apps for example).

- Have option for selecting theme, light or dark, or let the system decide;
- Separate theming of the UI from the map itself. I prefer brighter map for better visiblity;

**Comment by angelinn** [comment]
Light and dark mode have been implemented. Test version 3.5 and let me know if you have any suggestions.

**Comment by darkhunterbg** [comment]
Work great, also UI redesign. Was there a problem with detecting system theme on startup?
